version: "3"

tasks:
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:
      - task: generate
  vendor: ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
    desc: "go mod vendor"
    cmds: ## Тут описываем необходимые bash-команды
      - go mod tidy
      - go mod vendor
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen
    desc: "Generate code from proto files"
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc -I ./proto ./proto/api.proto --go_out=./ --go_opt=paths=source_relative --go-grpc_out=./ --go-grpc_opt=paths=source_relative